FROM public.ecr.aws/lambda/python:3.11

# Copy requirements file
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code
COPY ChatGenGoogle.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "ChatGenGoogle.lambda_handler" ]
